/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufes.gi.ui.sensormonitoramento;

import com.ufes.gi.dao.Sensor;
import com.ufes.gi.dao.SensorDAO;
import com.ufes.gi.dao.SensorMonitoramento;
import com.ufes.gi.dao.SensorMonitoramentoDAO;
import com.ufes.gi.dao.TipoFalha;
import com.ufes.gi.dao.TipoFalhaDAO;
import com.ufes.gi.dao.TipoMonitoramento;
import com.ufes.gi.dao.TipoMonitoramentoDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author joever
 */
public class CadastroSM extends javax.swing.JInternalFrame {
    List<Sensor> mySensores = new ArrayList<>();
    List<TipoMonitoramento> myTMs = new ArrayList<>();
    List<TipoFalha> myTFs = new ArrayList<>();
    String CPF = "";
    /**
     * Creates new form CadastroRede
     * @param myCPF
     */
    public CadastroSM(String myCPF) {
        initComponents();
        CPF = myCPF;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMedia = new javax.swing.JTextField();
        txtDiferenca = new javax.swing.JTextField();
        listaSensor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        listaTM = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        listaTF = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Cadastrar Sensor Monitoramento");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel3.setText("Sensor: ");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Média de Valores: ");

        jLabel5.setText("Diferença Máxima [%]: ");

        jLabel9.setText("Tipo de Monitoramento: ");

        jLabel10.setText("Tipo de Falha: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaSensor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiferenca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaTM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaTF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(listaSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(listaTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(listaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiferenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastraSM(SensorMonitoramento mySM){
        SensorMonitoramentoDAO myDAO = new SensorMonitoramentoDAO();
        if (myDAO.adiciona(mySM)){
            JOptionPane.showMessageDialog(rootPane, "Definições de Monitoramento e Falha do sensor cadastradas com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            txtMedia.setText("");
            txtDiferenca.setText("");
            listaSensor.grabFocus();
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Falha nas Definições de Monitoramento e Falha do sensor cadastrado!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtMedia.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar a média de valores gerados para esse tipo de monitoramento.", "Aviso", WIDTH);
            txtMedia.grabFocus();
        }
        if (txtDiferenca.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar a diferência máxima em % para os valores gerados por esse tipo de monitoramento.", "Aviso", WIDTH);
            txtDiferenca.grabFocus();
        }
        else {
            SensorMonitoramento newSM = new SensorMonitoramento();
            newSM.setIdSensor(mySensores.get(listaSensor.getSelectedIndex()).getIdSensor());
            newSM.setCpf(CPF);
            newSM.setIdTM(myTMs.get(listaTM.getSelectedIndex()).getCodigo());
            newSM.setIdTF(myTFs.get(listaTF.getSelectedIndex()).getIdTipoFalha());
            newSM.setMedia(Integer.parseInt(txtMedia.getText()));
            newSM.setDiferenca(Integer.parseInt(txtDiferenca.getText()));
            cadastraSM(newSM);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        SensorDAO mySensorDAO = new SensorDAO();
        mySensores = mySensorDAO.getSensores();
        mySensores.stream().forEach((mySensor) -> {
            listaSensor.addItem(mySensor.getNome());
        });
        
        TipoMonitoramentoDAO myTMDAO = new TipoMonitoramentoDAO();
        myTMs = myTMDAO.getTiposMonitoramento();
        myTMs.stream().forEach((myTM) -> {
            listaTM.addItem(myTM.getNome());
        });
        
        TipoFalhaDAO myTFDAO = new TipoFalhaDAO();
        myTFs = myTFDAO.getTiposFalhas();
        myTFs.stream().forEach((myTF) -> {
            listaTF.addItem(myTF.getNome());
        });
        
        listaSensor.grabFocus();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> listaSensor;
    private javax.swing.JComboBox<String> listaTF;
    private javax.swing.JComboBox<String> listaTM;
    private javax.swing.JTextField txtDiferenca;
    private javax.swing.JTextField txtMedia;
    // End of variables declaration//GEN-END:variables
}
