/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simulador;

import static java.awt.image.ImageObserver.ERROR;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import simulador.BancoUtil.*;
/**
 *
 * @author Joever
 */
public class RSSF extends javax.swing.JFrame {

    /**
     * Creates new form RSSF
     */
    public boolean parar = false;
    public String[][] sTipo = null;
    Thread t1;
    
    public RSSF() {
        this.t1 = new Thread() {
            public void run() {
                atualiza();
            }
        };
        initComponents();
        sTipo = BancoUtil.sTipo();
        Carrega(DadosTipo,sTipo);
    }
    
    private void Carrega(JComboBox DadosTipo, String[][] sTipo) {
        if (sTipo != null){
            if (sTipo.length > 0){
                for (int i=0;i<sTipo.length;i++){
                    DadosTipo.addItem(sTipo[i][0]+" - "+sTipo[i][1]+" - "+sTipo[i][2]);
                }
            }
        }
    }
    
    public void atualiza() {
        Integer cont, minimo, maximo;
        Double valor, tempo;
        
        //Verificações
        if (vTempo.getText().length() > 0)
            tempo = Double.parseDouble(vTempo.getText())*1000;
        else
            tempo = 10000.0; //Padrão 10s
        
        if (vMinimo.getText().length() > 0)
            minimo = Integer.parseInt(vMinimo.getText());
        else
            minimo = 20; //Padrão valores entre 20 - 40
        
        if (vMaximo.getText().length() > 0)
            maximo = Integer.parseInt(vMaximo.getText()) - minimo;
        else
            maximo = 0; //Padrão valores entre 20 - 40
        //Início do loop
        try {
            while (true){
                Date data = new Date();
                valor = minimo + (maximo*Math.random());
                valor = Math.rint(valor*100)/100;
                if (!BancoUtil.iEntrada(Integer.parseInt(sTipo[DadosTipo.getSelectedIndex()][0]),valor.toString(),data)) {
                    JOptionPane.showMessageDialog(rootPane, "Não foi possível incluir o registro!", "Erro", ERROR);
                }
                else {
                    cont = Integer.parseInt(vQuant.getText()) + 1;
                    vQuant.setText(cont.toString());
                }
                if (parar) {
                    vAndamento.setIndeterminate(false);
                    return;
                }
                Thread.sleep(tempo.longValue());
            }
        }catch (SQLException ex) {
            Logger.getLogger(RSSF.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            return;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vMinimo = new javax.swing.JTextField();
        vMaximo = new javax.swing.JTextField();
        vTempo = new javax.swing.JTextField();
        bSimular = new javax.swing.JButton();
        bParar = new javax.swing.JButton();
        bFechar = new javax.swing.JButton();
        vAndamento = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        vQuant = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DadosTipo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simular Sensor");
        setResizable(false);

        bSimular.setText("Simular");
        bSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimularActionPerformed(evt);
            }
        });

        bParar.setText("Parar");
        bParar.setEnabled(false);
        bParar.setPreferredSize(new java.awt.Dimension(67, 23));
        bParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPararActionPerformed(evt);
            }
        });

        bFechar.setText("Fechar");
        bFechar.setPreferredSize(new java.awt.Dimension(67, 23));
        bFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFecharActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de inclusões: ");

        vQuant.setText("0");

        jLabel2.setText("Mínimo");

        jLabel3.setText("Máximo");

        jLabel4.setText("tempo(s)");

        jLabel5.setText("Tipo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vAndamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSimular, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bParar, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vQuant)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DadosTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(vMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(vMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(vTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimular)
                    .addComponent(bParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(2, 2, 2)
                            .addComponent(vMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(2, 2, 2)
                            .addComponent(vMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(vTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DadosTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vAndamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vQuant)))
        );

        bSimular.setSize(75, 23);
        bParar.setSize(75, 23);
        bFechar.setSize(75, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharActionPerformed
        // TODO add your handling code here:
        if (t1.getState() != Thread.State.NEW) {
            t1.interrupt();
        }
        this.dispose();
    }//GEN-LAST:event_bFecharActionPerformed

    private void bSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimularActionPerformed
        // TODO add your handling code here:
        bSimular.setEnabled(false);
        bFechar.setEnabled(false);
        bParar.setEnabled(true);
        if (t1.getState() == Thread.State.NEW) {
            vAndamento.setIndeterminate(true);
            t1.start();
        }
        else {
            parar = false;
            if (t1.getState() == Thread.State.TERMINATED) {
                this.t1 = new Thread() {
                    public void run() {
                        atualiza();
                    }
                };
                vAndamento.setIndeterminate(true);
                t1.start();
            }
        }
    }//GEN-LAST:event_bSimularActionPerformed

    private void bPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPararActionPerformed
        // TODO add your handling code here:
        parar = true;
        bParar.setEnabled(false);
        bFechar.setEnabled(true);
        bSimular.setEnabled(true);
    }//GEN-LAST:event_bPararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSSF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSSF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSSF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSSF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSSF().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DadosTipo;
    private javax.swing.JButton bFechar;
    private javax.swing.JButton bParar;
    private javax.swing.JButton bSimular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar vAndamento;
    private javax.swing.JTextField vMaximo;
    private javax.swing.JTextField vMinimo;
    private javax.swing.JLabel vQuant;
    private javax.swing.JTextField vTempo;
    // End of variables declaration//GEN-END:variables
}
