/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufes.gi.ui.modelosensor;

import com.ufes.gi.dao.ModeloSensor;
import com.ufes.gi.dao.ModeloSensorDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author joever
 */
public class ConsultaMS extends javax.swing.JInternalFrame {
    List<ModeloSensor> myMSs = new ArrayList<>();
    Integer indice = 0;
    /**
     * Creates new form ModeloSensor
     */
    public ConsultaMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtNSensores = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        listaMS = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Definir Modelos de Sensores");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Código: ");

        jLabel2.setText("Nome: ");

        jLabel3.setText("Descrição: ");

        jLabel4.setText("Número possível de sensores: ");

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Lista: ");

        listaMS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaMSItemStateChanged(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNSensores, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaMS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButton1)
                .addGap(24, 24, 24)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(listaMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNSensores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluiMS(Integer myCodigo){
        ModeloSensorDAO myDAO = new ModeloSensorDAO();
        if (myDAO.deleta(myCodigo)){
            indice = 0;
            JOptionPane.showMessageDialog(rootPane, "Modelo de Sensor excluído com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            listaMS.removeAllItems();
            formInternalFrameOpened(null);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Falha ao excluir modelo de sensor!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    private void AtualizaMS(ModeloSensor myMS){
        ModeloSensorDAO myDAO = new ModeloSensorDAO();
        if (myDAO.atualiza(myMS)){
            indice = listaMS.getSelectedIndex();
            JOptionPane.showMessageDialog(rootPane, "Modelo de Sensor alterado com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            listaMS.removeAllItems();
            formInternalFrameOpened(null);            
            txtNome.grabFocus();
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Falha ao alterar modelo de sensor!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        ModeloSensorDAO myDAO = new ModeloSensorDAO();
        myMSs = myDAO.getModeloSensores();
        myMSs.stream().forEach((myMS) -> {
            listaMS.addItem(myMS.getNome());
        });
        listaMS.setSelectedIndex(indice);
        txtCodigo.setEditable(false);
        txtCodigo.setText(myMSs.get(indice).getIdModeloSensor().toString());
        txtNome.setText(myMSs.get(indice).getNome());
        txtDescricao.setText(myMSs.get(indice).getDescricao());
        txtNSensores.setText(myMSs.get(indice).getnSensores().toString());
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtNome.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar o Nome para o Modelo do Sensor.", "Aviso", WIDTH);
            txtNome.grabFocus();
        }
        else if (txtDescricao.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar a Descrição do Modelo do Sensor.", "Aviso", WIDTH);
            txtDescricao.grabFocus();
        }
        else if (txtNSensores.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar o número de sensores que o nó sensor poderá ter.", "Aviso", WIDTH);
            txtDescricao.grabFocus();
        }
        else {
            ModeloSensor newMS = new ModeloSensor();
            newMS.setIdModeloSensor(Integer.parseInt(txtCodigo.getText()));
            newMS.setNome(txtNome.getText());
            newMS.setDescricao(txtDescricao.getText());
            newMS.setnSensores(Integer.parseInt(txtNSensores.getText()));
            AtualizaMS(newMS);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listaMSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaMSItemStateChanged
        // TODO add your handling code here:
        myMSs.stream().forEach((myMS) -> {
            if (myMS.getNome().equals(listaMS.getItemAt(listaMS.getSelectedIndex()))) {
                txtCodigo.setText(myMS.getIdModeloSensor().toString());
                txtNome.setText(myMS.getNome());
                txtDescricao.setText(myMS.getDescricao());
                txtNSensores.setText(myMS.getnSensores().toString());
            }
        });
    }//GEN-LAST:event_listaMSItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int resposta;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Confirma a exclusão do Modelo de Sensor "+txtNome.getText()+"?","Excluir Modelo Sensor?",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (resposta == JOptionPane.YES_NO_OPTION) {
            excluiMS(Integer.parseInt(txtCodigo.getText()));
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> listaMS;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNSensores;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
