/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufes.gi.ui.tipofalha;

import com.ufes.gi.dao.TipoFalha;
import com.ufes.gi.dao.TipoFalhaDAO;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author joever
 */
public class ConsultaTF extends javax.swing.JInternalFrame {
    List<TipoFalha> myTFs = new ArrayList<>();
    Integer indice = 0;
    /**
     * Creates new form CadastroTF
     */
    public ConsultaTF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtV1 = new javax.swing.JTextField();
        txtV2 = new javax.swing.JTextField();
        txtV3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        listaTF = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro Tipo de Falha");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Código: ");

        jLabel2.setText("Nome: ");

        jLabel3.setText("Descrição: ");

        jLabel4.setText("Valor 1: ");

        jLabel5.setText("Valor 2: ");

        jLabel6.setText("Valor 3: ");

        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Lista: ");

        listaTF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaTFItemStateChanged(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtV1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtV2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtV3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaTF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(listaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluiTF(Integer myCodigo){
        TipoFalhaDAO myDAO = new TipoFalhaDAO();
        if (myDAO.deleta(myCodigo)){
            indice = 0;
            JOptionPane.showMessageDialog(rootPane, "Tipo de Falha excluído com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            listaTF.removeAllItems();
            formInternalFrameOpened(null);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Falha ao excluir tipo de Falha!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    private void atualizaTF(TipoFalha myTF){
        TipoFalhaDAO myDAO = new TipoFalhaDAO();
        if (myDAO.atualiza(myTF)){
            indice = listaTF.getSelectedIndex();
            JOptionPane.showMessageDialog(rootPane, "Tipo de Falha atualizada com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            listaTF.removeAllItems();
            formInternalFrameOpened(null);
            txtNome.grabFocus();
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Falha ao atualizar tipo de Falha!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        TipoFalhaDAO myDAO = new TipoFalhaDAO();
        myTFs = myDAO.getTiposFalhas();
        myTFs.stream().forEach((myTF) -> {
            listaTF.addItem(myTF.getNome());
        });
        listaTF.setSelectedIndex(indice);
        txtCodigo.setEditable(false);
        txtCodigo.setText(myTFs.get(indice).getIdTipoFalha().toString());
        txtNome.setText(myTFs.get(indice).getNome());
        txtDescricao.setText(myTFs.get(indice).getDescricao());
        if (myTFs.get(indice).getValor1()!= null)
            txtV1.setText(myTFs.get(indice).getValor1().toString());
        else
            txtV1.setText("0");
        if (myTFs.get(indice).getValor2() != null)
            txtV2.setText(myTFs.get(indice).getValor2().toString());
        else
            txtV2.setText("0");
        if (myTFs.get(indice).getValor3() != null)
            txtV3.setText(myTFs.get(indice).getValor3().toString());
        else
            txtV3.setText("0");
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtV1.getText().length() == 0)
            txtV1.setText("0");
        if (txtV2.getText().length() == 0)
            txtV2.setText("0");
        if (txtV3.getText().length() == 0)
            txtV3.setText("0");
        if (txtNome.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar o Nome para o tipo de falha.", "Aviso", WIDTH);
            txtNome.grabFocus();
        }
        else if (txtDescricao.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar a Descrição do tipo de falha.", "Aviso", WIDTH);
            txtDescricao.grabFocus();
        }
        else {
            TipoFalha newTF = new TipoFalha();
            newTF.setIdTipoFalha(Integer.parseInt(txtCodigo.getText()));
            newTF.setNome(txtNome.getText());
            newTF.setDescricao(txtDescricao.getText());
            newTF.setValor1(Integer.parseInt(txtV1.getText()));
            newTF.setValor2(Integer.parseInt(txtV2.getText()));
            newTF.setValor3(Integer.parseInt(txtV3.getText()));
            atualizaTF(newTF);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listaTFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaTFItemStateChanged
        // TODO add your handling code here:
        myTFs.stream().forEach((myTF) -> {
            if (myTF.getNome().equals(listaTF.getItemAt(listaTF.getSelectedIndex()))) {
                txtCodigo.setText(myTF.getIdTipoFalha().toString());
                txtNome.setText(myTF.getNome());
                txtDescricao.setText(myTF.getDescricao());
                if (myTF.getValor1() != null)
                    txtV1.setText(myTF.getValor1().toString());
                else
                    txtV1.setText("0");
                if (myTF.getValor2() != null)
                    txtV2.setText(myTF.getValor2().toString());
                else
                    txtV2.setText("0");
                if (myTF.getValor3() != null)
                    txtV3.setText(myTF.getValor3().toString());
                else
                    txtV3.setText("0");
            }
        });
    }//GEN-LAST:event_listaTFItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int resposta;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Confirma a exclusão do Tipo de Falha "+txtNome.getText()+"?","Excluir Tipo Falha?",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (resposta == JOptionPane.YES_NO_OPTION) {
            excluiTF(Integer.parseInt(txtCodigo.getText()));
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> listaTF;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtV1;
    private javax.swing.JTextField txtV2;
    private javax.swing.JTextField txtV3;
    // End of variables declaration//GEN-END:variables
}
