/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufes.gi.ui.redesensor;

import com.ufes.gi.dao.Rede;
import com.ufes.gi.dao.RedeDAO;
import com.ufes.gi.dao.RedeSensores;
import com.ufes.gi.dao.RedeSensoresDAO;
import com.ufes.gi.dao.Sensor;
import com.ufes.gi.dao.SensorDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author joever
 */
public class CadastroRedeSensor extends javax.swing.JInternalFrame {
    List<Rede> myRedes = new ArrayList<>();
    List<Sensor> mySensores = new ArrayList<>();
    String CPF = "";
    /**
     * Creates new form CadastroRede
     * @param myCPF
     */
    public CadastroRedeSensor(String myCPF) {
        initComponents();
        CPF = myCPF;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUnidades = new javax.swing.JTextField();
        txtBateriaInicial = new javax.swing.JTextField();
        listaRede = new javax.swing.JComboBox<>();
        listaSensor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtTempoAtivo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGastoBateria = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTempoColeta = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastrar Sensor na Rede");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Código: ");

        jLabel2.setText("Rede:");

        jLabel3.setText("Sensor: ");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Número de Unidades: ");

        jLabel5.setText("Nível de Bateria Inicial [%]:");

        jLabel6.setText("Tempo Ativo [s]: ");

        jLabel7.setText("Gasto de Bateria [%/s]: ");

        jLabel8.setText("Tempo entre coletas [s]: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaRede, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaSensor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBateriaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTempoAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGastoBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 20, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTempoColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(listaRede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(listaSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtBateriaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTempoAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtGastoBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTempoColeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastraRedeSensor(RedeSensores myRedeSensor){
        RedeSensoresDAO myDAO = new RedeSensoresDAO();
        if (myDAO.adiciona(myRedeSensor)){
            JOptionPane.showMessageDialog(rootPane, "Sensor cadastrado na Rede com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            txtCodigo.setText(myDAO.getProxId().toString());
            txtUnidades.setText("");
            txtBateriaInicial.setText("");
            txtTempoAtivo.setText("");
            txtGastoBateria.setText("");
            txtTempoColeta.setText("");
            listaRede.grabFocus();
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Falha ao cadastrado sensor na rede!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String gastoBateria = txtGastoBateria.getText();
        gastoBateria = gastoBateria.replace(",", ".");
        if (txtUnidades.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar o Número de unidades desse sensor para a Rede.", "Aviso", WIDTH);
            txtUnidades.grabFocus();
        }
        if (txtBateriaInicial.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar o nível de bateria inicial desse sensor para a Rede.", "Aviso", WIDTH);
            txtBateriaInicial.grabFocus();
        }
        if (txtTempoAtivo.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar o tempo que esse sensor ficou ativo.", "Aviso", WIDTH);
            txtTempoAtivo.grabFocus();
        }
        if (txtGastoBateria.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar o gasto de bateria desse sensor.", "Aviso", WIDTH);
            txtGastoBateria.grabFocus();
        }
        if (txtTempoColeta.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar o entre coletas desse sensor na rede.", "Aviso", WIDTH);
            txtTempoColeta.grabFocus();
        }
        else {
            RedeSensores newRedeSensor = new RedeSensores();
            newRedeSensor.setIdRedeSensor(Integer.parseInt(txtCodigo.getText()));
            newRedeSensor.setIdRede(myRedes.get(listaRede.getSelectedIndex()).getIdRede());
            newRedeSensor.setCpf(CPF);
            newRedeSensor.setIdSensor(mySensores.get(listaSensor.getSelectedIndex()).getIdSensor());
            newRedeSensor.setUnidades(Integer.parseInt(txtUnidades.getText()));
            newRedeSensor.setBateriaInicial(Integer.parseInt(txtBateriaInicial.getText()));
            newRedeSensor.setTempoAtivo(Integer.parseInt(txtTempoAtivo.getText()));
            newRedeSensor.setGastoBateria(Double.parseDouble(gastoBateria));
            newRedeSensor.setTempoColeta(Integer.parseInt(txtTempoColeta.getText()));
            cadastraRedeSensor(newRedeSensor);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        RedeSensoresDAO myDAO = new RedeSensoresDAO();
        txtCodigo.setText(myDAO.getProxId().toString());
        txtCodigo.setEditable(false);
        
        RedeDAO myRedeDAO = new RedeDAO();
        myRedes = myRedeDAO.getRedes();
        myRedes.stream().forEach((myRede) -> {
            listaRede.addItem(myRede.getNome());
        });
        
        SensorDAO mySensorDAO = new SensorDAO();
        mySensores = mySensorDAO.getSensores();
        mySensores.stream().forEach((mySensor) -> {
            listaSensor.addItem(mySensor.getNome());
        });
        
        listaRede.grabFocus();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> listaRede;
    private javax.swing.JComboBox<String> listaSensor;
    private javax.swing.JTextField txtBateriaInicial;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtGastoBateria;
    private javax.swing.JTextField txtTempoAtivo;
    private javax.swing.JTextField txtTempoColeta;
    private javax.swing.JTextField txtUnidades;
    // End of variables declaration//GEN-END:variables
}
