/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufes.gi.ui.sobre;

/**
 *
 * @author joever
 */
public class Sobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sobre
     */
    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textoSobre = new javax.swing.JTextPane();

        setClosable(true);

        textoSobre.setEditable(false);
        textoSobre.setContentType("text/html"); // NOI18N
        textoSobre.setText("<p align=justify>&nbsp;&nbsp;&nbsp;Gerador de Informação de Contexto que simula redes de sensores sem fio RSSF. Para cada sensor na rede são geradas threds que ficam gerando os arquivos XML de contexto segundo as configurações realizadas para rede/sensor/tipo de monitoramento</p>\n\n<p align=left>Autor: <b>Joéver Silva Hoffman</b><br>\n\n<p align=center>Vitória, ES<br>\n2016</p>");
        textoSobre.setOpaque(false);
        jScrollPane1.setViewportView(textoSobre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textoSobre;
    // End of variables declaration//GEN-END:variables
}
